### ISSUE TITLE
Bug when using S3 in drive.

### ISSUE THREAD

**Issue by joshmanders** [batosai/attachment-advanced#1]
Everything seems to work, except I get this error in my console when I use `s3` for my Adonis Drive destination and using Digital Ocean Spaces.

```Error: ENOENT: no such file or directory, open '/[redacted]/https:/[redacted].nyc3.digitaloceanspaces.com/clp7ooil40003qnry95pn46jj.jpg'```

Edit://

This seems to be happening in the `getDimensions()` helper.

**Comment by batosai** [comment]
Hello,
May I know why you closed this issue?
